import type { Metadata } from "next";
import { Bitcount_Grid_Single } from "next/font/google";
import "./globals.css";


const bitcountGridSingle = Bitcount_Grid_Single({
  variable: "--font-bitcount-single",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${bitcountGridSingle.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
