import type { Metadata } from "next";
import { Bitcount_Grid_Single } from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";


const bitcountGridSingle = Bitcount_Grid_Single({
  variable: "--font-bitcount-single",
  subsets: ["latin"],
  fallback: ['Arial', 'sans-serif'],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <body
          className={`${bitcountGridSingle.variable} antialiased`}
        >
          {children}
        </body>
      </html>
    </StoreProvider>
  );
}
